os: linux
language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-23.0.1
    - android-23
before_install:
  - cd hangzhou_mandarim_app
  - yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;23.0.2"
  - yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;23.0.2"
  - nvm install && nvm use
  - npm install -g "npm@$(jq -r '.engines.npm' package.json)"
  - cd android
  - chmod +x gradlew
install:
  - npm ci
script:
  - cd ..
  - "./android/gradlew assembleRelease -p android/"